from enum import Enum


class Role(str, Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    PROJECT_ADMIN = "PROJECT_ADMIN"
    ONTOLOGY_MANAGER = "ONTOLOGY_MANAGER"
    DATA_MANAGER = "DATA_MANAGER"
    EXTRACTION_MANAGER = "EXTRACTION_MANAGER"
    REVIEWER = "REVIEWER"
    VIEWER = "VIEWER"
    API_CLIENT = "API_CLIENT"


class ProjectStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"


class OntologyVersionStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class OntologyElementStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"


class SourceType(str, Enum):
    CSV = "CSV"
    EXCEL = "EXCEL"
    TXT = "TXT"
    PDF = "PDF"


class SourceStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    PROFILED = "PROFILED"
    EXTRACTION_READY = "EXTRACTION_READY"
    FAILED = "FAILED"


class SourcePreviewStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    FAILED = "FAILED"


class SourceSegmentType(str, Enum):
    SHEET = "SHEET"
    ROW = "ROW"
    CELL = "CELL"
    PAGE = "PAGE"
    SECTION = "SECTION"
    PARAGRAPH = "PARAGRAPH"
    CHUNK = "CHUNK"


class PropertyDataType(str, Enum):
    STRING = "STRING"
    TEXT = "TEXT"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    URI = "URI"


class ProfileInferredType(str, Enum):
    STRING = "STRING"
    TEXT = "TEXT"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    URI = "URI"
    EMPTY = "EMPTY"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class Cardinality(str, Enum):
    ONE_TO_ONE = "ONE_TO_ONE"
    ONE_TO_MANY = "ONE_TO_MANY"
    MANY_TO_ONE = "MANY_TO_ONE"
    MANY_TO_MANY = "MANY_TO_MANY"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    MULTIPLE = "MULTIPLE"


class ValidationStatus(str, Enum):
    NOT_VALIDATED = "NOT_VALIDATED"
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class CandidateReviewStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    NEEDS_DISCUSSION = "NEEDS_DISCUSSION"


class PublishStatus(str, Enum):
    NOT_PUBLISHED = "NOT_PUBLISHED"
    PUBLISHED = "PUBLISHED"
    ROLLED_BACK = "ROLLED_BACK"


class ExtractionJobStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_FAILED = "PARTIAL_FAILED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RETRYING = "RETRYING"


class ModelRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class CandidateValidationCode(str, Enum):
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    INVALID_EVIDENCE_REFERENCE = "INVALID_EVIDENCE_REFERENCE"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    ONTOLOGY_ELEMENT_NOT_FOUND = "ONTOLOGY_ELEMENT_NOT_FOUND"
    RELATION_ENDPOINT_MISSING = "RELATION_ENDPOINT_MISSING"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    PROVIDER_OUTPUT_INVALID = "PROVIDER_OUTPUT_INVALID"


class CandidateKind(str, Enum):
    ENTITY = "ENTITY"
    RELATION = "RELATION"
    PROPERTY_VALUE = "PROPERTY_VALUE"


class ValidationJobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class ValidationRuleCode(str, Enum):
    CLASS_EXISTS = "CLASS_EXISTS"
    RELATION_EXISTS = "RELATION_EXISTS"
    RELATION_DOMAIN_RANGE = "RELATION_DOMAIN_RANGE"
    RELATION_DIRECTION = "RELATION_DIRECTION"
    REQUIRED_PROPERTY = "REQUIRED_PROPERTY"
    DATATYPE = "DATATYPE"
    CARDINALITY = "CARDINALITY"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    ORPHAN_NODE = "ORPHAN_NODE"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    ONTOLOGY_VERSION_MISMATCH = "ONTOLOGY_VERSION_MISMATCH"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"


class ValidationResultSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    FAILED = "FAILED"


class ReviewTaskStatus(str, Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_REVIEW = "IN_REVIEW"
    DECIDED = "DECIDED"
    CANCELLED = "CANCELLED"


class ReviewDecisionType(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    MODIFY_AND_APPROVE = "MODIFY_AND_APPROVE"


class CorrectionStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPLIED = "APPLIED"
    SUPERSEDED = "SUPERSEDED"


class AuditEventType(str, Enum):
    VALIDATION_JOB_CREATED = "VALIDATION_JOB_CREATED"
    VALIDATION_RESULT_RECORDED = "VALIDATION_RESULT_RECORDED"
    REVIEW_TASK_CREATED = "REVIEW_TASK_CREATED"
    REVIEW_TASK_ASSIGNED = "REVIEW_TASK_ASSIGNED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    REVIEW_DECISION_RECORDED = "REVIEW_DECISION_RECORDED"
    PUBLISH_JOB_CREATED = "PUBLISH_JOB_CREATED"
    PUBLISH_JOB_COMPLETED = "PUBLISH_JOB_COMPLETED"
    PUBLISHED_GRAPH_VERSION_CREATED = "PUBLISHED_GRAPH_VERSION_CREATED"
    PUBLISHED_GRAPH_CURRENT_POINTER_UPDATED = "PUBLISHED_GRAPH_CURRENT_POINTER_UPDATED"


class PublishJobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_FAILED = "PARTIAL_FAILED"
    FAILED = "FAILED"


class PublishEligibilityReasonCode(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    NOT_APPROVED_OR_MODIFIED = "NOT_APPROVED_OR_MODIFIED"
    PENDING = "PENDING"
    REJECTED = "REJECTED"
    NEEDS_DISCUSSION = "NEEDS_DISCUSSION"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    BROKEN_EVIDENCE = "BROKEN_EVIDENCE"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    WARNING_REASON_REQUIRED = "WARNING_REASON_REQUIRED"
    ALREADY_PUBLISHED = "ALREADY_PUBLISHED"
    ONTOLOGY_VERSION_MISMATCH = "ONTOLOGY_VERSION_MISMATCH"
    PUBLISH_PERMISSION_REQUIRED = "PUBLISH_PERMISSION_REQUIRED"
    CORRECTION_DIFF_REQUIRED = "CORRECTION_DIFF_REQUIRED"


class QualityDrilldownTarget(str, Enum):
    REVIEW_INBOX = "review_inbox"
    PUBLISH_JOBS = "publish_jobs"
    PUBLISHED_GRAPH = "published_graph"


class EvaluationDatasetStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class GoldenSetItemKind(str, Enum):
    ENTITY = "ENTITY"
    RELATION = "RELATION"
    PROPERTY_VALUE = "PROPERTY_VALUE"
    EVIDENCE_LINK = "EVIDENCE_LINK"


class PromptExperimentStatus(str, Enum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class QualityMetricGroup(str, Enum):
    COMPLETENESS = "COMPLETENESS"
    CONSISTENCY = "CONSISTENCY"
    TRACEABILITY = "TRACEABILITY"
    VALIDATION = "VALIDATION"
    REVIEW = "REVIEW"
    DUPLICATE = "DUPLICATE"
    RELATION_DENSITY = "RELATION_DENSITY"


class QualityMetricUnit(str, Enum):
    COUNT = "COUNT"
    RATE = "RATE"
    RATIO = "RATIO"
    PERCENT = "PERCENT"


class SearchResultKind(str, Enum):
    PUBLISHED_ENTITY = "PUBLISHED_ENTITY"
    PUBLISHED_RELATION = "PUBLISHED_RELATION"
    SOURCE = "SOURCE"
    SOURCE_CHUNK = "SOURCE_CHUNK"
    EVIDENCE = "EVIDENCE"
    LINEAGE = "LINEAGE"


class VectorAdapterStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    FALLBACK_KEYWORD = "FALLBACK_KEYWORD"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class VectorFallbackReason(str, Enum):
    VECTOR_DB_NOT_CONFIGURED = "VECTOR_DB_NOT_CONFIGURED"
    INDEX_NOT_READY = "INDEX_NOT_READY"
    ADAPTER_ERROR = "ADAPTER_ERROR"
    KEYWORD_FALLBACK_USED = "KEYWORD_FALLBACK_USED"


class RagAnswerState(str, Enum):
    ANSWERED = "ANSWERED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ERROR = "ERROR"


class RagCitationKind(str, Enum):
    EVIDENCE_CHUNK = "EVIDENCE_CHUNK"
    SOURCE_CHUNK = "SOURCE_CHUNK"
    PUBLISHED_ENTITY = "PUBLISHED_ENTITY"
    PUBLISHED_RELATION = "PUBLISHED_RELATION"


class GraphExploreState(str, Enum):
    READY = "READY"
    SAFE_TOO_LARGE = "SAFE_TOO_LARGE"
    EMPTY = "EMPTY"
    ERROR = "ERROR"


class ExternalApiAuthMode(str, Enum):
    DEV_AUTH = "DEV_AUTH"
